name: flutter_shared_utils
description: "A Flutter package that provides Utils."
version: 1.0.0
homepage:
repository: https://github.com/Abubakarshaikh/flutter_shared_utils

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  clock: ^1.1.1
  convert: ^3.1.1
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  plugin:
    platforms:

      some_platform:
        pluginClass: somePluginClass
